# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# Position Controllers ---------------------------------------
joint1_position:
  type: position_controllers/JointPositionController
  joint: joint1

joint2_position:
  type: position_controllers/JointPositionController
  joint: joint2

joint3_position:
  type: position_controllers/JointPositionController
  joint: joint3

joint4_position:
  type: position_controllers/JointPositionController
  joint: joint4

joint5_position:
  type: position_controllers/JointPositionController
  joint: joint5

joint6_position:
  type: position_controllers/JointPositionController
  joint: joint6

gripper_position:
  type: position_controllers/JointPositionController
  joint: gripper

gripper_sub_position:
  type: position_controllers/JointPositionController
  joint: gripper_sub
